/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vstorepresentacion;

import com.mycompany.vstoredetallepelicula.FuncionalidadDetallePelicula;
import com.mycompany.vstoredetallepelicula.IFuncionalidadDetallePelicula;
import com.mycompany.vstoredto.dtos.PeliculaDTO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class FormPeliculaDetalle extends javax.swing.JFrame {

    IFuncionalidadDetallePelicula funcionalidadDetallePelicula;

    /**
     * Creates new form FormPeliculaDetalle
     */
    public FormPeliculaDetalle(String nombre) {
        initComponents();
        funcionalidadDetallePelicula = new FuncionalidadDetallePelicula();
        PeliculaDTO pelicula = funcionalidadDetallePelicula.consultarPelicula(nombre);
        labelDescripcion.setText(pelicula.getDescripcion());
        labelNombre.setText(pelicula.getNombre());
        BufferedImage image = null;
        try {
            image = ImageIO.read(new ByteArrayInputStream(pelicula.getImg()));
            labelImagen.setIcon(new ImageIcon(image));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labelImagen = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Nombre");
        panelFondo.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        labelDescripcion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        labelDescripcion.setText("Descripción");
        panelFondo.add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VSTORE.drawio.png"))); // NOI18N
        panelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        panelFondo.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Favorito");
        panelFondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 140, 40));
        panelFondo.add(labelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 120, 170));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoblue.jpg"))); // NOI18N
        panelFondo.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
