
package com.mycompany.vstorepresentacion;


public class FormIniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form FormIniciarSecion
     */
    public FormIniciarSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        LogoVstore = new javax.swing.JLabel();
        IniciarSecion = new javax.swing.JLabel();
        TextUsuario = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContra = new javax.swing.JLabel();
        TextContra = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        FondoVstore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoVstore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VSTORE.drawio.png"))); // NOI18N
        PanelFondo.add(LogoVstore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        IniciarSecion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        IniciarSecion.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSecion.setText("Iniciar Seción");
        PanelFondo.add(IniciarSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        TextUsuario.setBackground(new java.awt.Color(0, 0, 0));
        TextUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TextUsuario.setForeground(new java.awt.Color(255, 255, 255));
        PanelFondo.add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 310, 50));

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        PanelFondo.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabelContra.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelContra.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContra.setText("Contraseña:");
        PanelFondo.add(jLabelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        TextContra.setBackground(new java.awt.Color(0, 0, 0));
        TextContra.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TextContra.setForeground(new java.awt.Color(255, 255, 255));
        PanelFondo.add(TextContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 310, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        PanelFondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        FondoVstore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoblue.jpg"))); // NOI18N
        PanelFondo.add(FondoVstore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1542, 840));

        getContentPane().add(PanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormIniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoVstore;
    private javax.swing.JLabel IniciarSecion;
    private javax.swing.JLabel LogoVstore;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPasswordField TextContra;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelContra;
    private javax.swing.JLabel jLabelUsuario;
    // End of variables declaration//GEN-END:variables
}
