/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vstorepresentacion;

import com.mycompany.vstoredto.dtos.UsuarioDTO;
import com.mycompany.vstoreiniciarsesion.FuncionalidadIniciarSesion;
import com.mycompany.vstoreiniciarsesion.IFuncionalidadIniciarSesion;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FormIniciarSesion extends javax.swing.JFrame {

    private IFuncionalidadIniciarSesion funcionalidadIniciarSesion;

    /**
     * Creates new form FormIniciarSecion
     */
    public FormIniciarSesion() {
        initComponents();
        funcionalidadIniciarSesion = new FuncionalidadIniciarSesion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        LogoVstore = new javax.swing.JLabel();
        IniciarSecion = new javax.swing.JLabel();
        TextUsuario = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContra = new javax.swing.JLabel();
        TextContra = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        FondoVstore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoVstore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VSTORE.drawio.png"))); // NOI18N
        PanelFondo.add(LogoVstore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        IniciarSecion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        IniciarSecion.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSecion.setText("Iniciar Seción");
        PanelFondo.add(IniciarSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        TextUsuario.setBackground(new java.awt.Color(0, 0, 0));
        TextUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TextUsuario.setForeground(new java.awt.Color(255, 255, 255));
        PanelFondo.add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 310, 50));

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        PanelFondo.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabelContra.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelContra.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContra.setText("Contraseña:");
        PanelFondo.add(jLabelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        TextContra.setBackground(new java.awt.Color(0, 0, 0));
        TextContra.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TextContra.setForeground(new java.awt.Color(255, 255, 255));
        PanelFondo.add(TextContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 310, 50));

        btnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        PanelFondo.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        PanelFondo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        FondoVstore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoblue.jpg"))); // NOI18N
        PanelFondo.add(FondoVstore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1542, 840));

        getContentPane().add(PanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (TextUsuario.getText().isBlank() || String.valueOf(TextContra.getPassword()).isBlank()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son necesarios");
            return;
        }
        UsuarioDTO usuario = new UsuarioDTO();

        usuario.setUsuario(TextUsuario.getText());
        usuario.setContrasenia(String.valueOf(TextContra.getPassword()));

        UsuarioDTO usuarioConsultado = funcionalidadIniciarSesion.iniciarSesion(usuario);
        if (usuarioConsultado == null) {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");

        }
        FormBuscarPelicula p = new FormBuscarPelicula(usuario);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoVstore;
    private javax.swing.JLabel IniciarSecion;
    private javax.swing.JLabel LogoVstore;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPasswordField TextContra;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelContra;
    private javax.swing.JLabel jLabelUsuario;
    // End of variables declaration//GEN-END:variables
}
